### ISSUE TITLE
Unable to delete or update individual rows

### ISSUE THREAD

**Issue by amw-zero** [enspirit/bmg#25]
Calling `delete` and `update` on a Bmg::Relation always results in the operation getting applied to the entire underlying table rather than only the rows in the relation.

For example:

`Bmg.sequel(:example, DB).restrict(id: 5).delete`

This will attempt to delete the entire `example` table, whereas I'd expect this to only delete the row with id = 5. 

Looking at the BMG code, it seems like [this is intentional](https://github.com/enspirit/bmg/blob/master/lib/bmg/sequel/relation.rb#L16). So first off, is there some other way of doing this that I don't know about? And second, do we want to be able to generate SQL for delete operations on subsets of tables?

cc @blambeau

**Comment by blambeau** [comment]
Hi @amw-zero, thanks for reaching out.

It's not really intentional. Bmg has a rather complete set of rules for updates on memory relvars, but the Sequel/SQL cannot reuse it easily. The architecture needs some refactoring and I never found the time to do so.

But yes, it's on the roadmap to improve updates to avoid those "bugs". I don't consider Bmg ready for updates, it's just an algebra until further notice.

**Comment by blambeau** [comment]
I would certainly consider help adding real update/delete/insert support on top of SQL relvars. Feel free to open PRs if you want to contribute.

Unless you see any reason to keep the Issue open, I'll close this.

**Comment by amw-zero** [comment]
Thanks for the reply. I may go ahead and try and implement this, it would be useful to what I'm working on.

You can close the issue, it's mostly the easiest way to communicate about something like this. Thanks!

**Comment by blambeau** [comment]
Great. Most updating logic is already implemented in the in-memory operator classes.

We should probably move them from there, to make them reusable in other contexts. Possibly they could be attached to the relation Type, or as yet another companion instance.
